### ISSUE TITLE
Support Access-Control-Allow-Credentials header

### ISSUE THREAD

**Issue by praneshr** [dgraph-io/dgraph-js-http#2]
Provide a way to define `credentials: 'include'` to the `isomorphic-fetch`.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials

**Comment by paulftw** [comment]
Since Dgraph servers don't use cookies and apps like Ratel are able to run queries and mutations without the `credentials: include` I personally don't see why this flag would be necessary.

Closing the issue as stale. Please re-open if there's a use case where setting the credentials thing is necessary.
